#!/bin/bash

if [ "$2" = "OADB/CMakelibOADB.pkg" ]; then
    sed -i 's/COMMON PWGPP PWG2 PWG3 PWG4 PWGLF/${ALIRSNLITE_SRC}\/OADB\/COMMON ${ALIRSNLITE_SRC}\/OADB\/PWGPP ${ALIRSNLITE_SRC}\/OADB\/PWG2 ${ALIRSNLITE_SRC}\/OADB\/PWG3 ${ALIRSNLITE_SRC}\/OADB\/PWG4 ${ALIRSNLITE_SRC}\/OADB\/PWGLF/' $1
#     sed -i 's/COMMON PWGPP PWG2 PWG3 PWG4 PWGLF/${ALIRSNLITE_SRC}\/OADB\/COMMON ${ALIRSNLITE_SRC}\/OADB\/PWGPP ${ALIRSNLITE_SRC}\/OADB\/PWG2 ${ALIRSNLITE_SRC}\/OADB\/PWG3 ${ALIRSNLITE_SRC}\/OADB\/PWG4' $1
fi
